# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: FEniCS-in-the-wild
author: Jørgen S. Dokken
copyright: "2024"
#logo:
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache

  # Set timeout for any example to 20 minutes
  timeout: 1800
# Define the name of the latex output file for PDF builds
# latex:
#   latex_documents:
#     targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/scientificcomputing/fenics-in-the-wild # Online location of your book
  path_to_book: . # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

  # Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"

sphinx:
  config:
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py
    codeautolink_concat_default: True
    intersphinx_mapping:
      basix : ["https://docs.fenicsproject.org/basix/main/python/", null]
      ffcx : ["https://docs.fenicsproject.org/ffcx/main/", null]
      ufl : ["https://docs.fenicsproject.org/ufl/main/", null]
      dolfinx : ["https://docs.fenicsproject.org/dolfinx/main/python", null]
      petsc4py: ["https://petsc.org/release/petsc4py", null]
      mpi4py: ["https://mpi4py.readthedocs.io/en/stable", null]
      numpy: ["https://numpy.org/doc/stable/", null]
      pyvista: ["https://docs.pyvista.org/", null]
      packaging: ["https://packaging.pypa.io/en/stable/", null]
      scifem: ["https://scientificcomputing.github.io/scifem/", null]

  extra_extensions:
    - 'sphinx.ext.autodoc'
    - 'sphinx.ext.intersphinx'
    - "sphinx_codeautolink"

# sphinx:
#   config:
# templates_path: ["_templates"]
# html_last_updated_fmt: "%b %d, %Y"
# suppress_warnings: ["mystnb.unknown_mime_type"]
# html_show_copyright: true
# html_show_sourcelink: false
# html_theme: pydata_sphinx_theme
# html_theme_options:
#   show_toc_level: 2
#   show_nav_level: 1
#   collapse_navigation: True
#   footer_start: ["copyright"]
#   footer_center: ["footer"]
#   footer_end: ["theme-version"]
#   use_edit_page_button: False
# html_context:
#   github_user: scientificcomputing
#   github_repo: fenics-in-the-wild
#   github_version: main
# html_sidebars:
#   "**": []

# html_sidebars:
#   "**": []
parse:
  myst_enable_extensions:
    - "amsmath"
    - "colon_fence"
    - "deflist"
    - "dollarmath"
    - "html_admonition"
    - "html_image"
    - "linkify"
    - "replacements"
    - "smartquotes"
    - "substitution"

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

exclude_patterns: [README.md]
