name: Build documentation

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

env:
  # Directory that will be published on github pages
  PUBLISH_DIR: ./_build/html
  DEB_PYTHON_INSTALL_LAYOUT: deb_system
  PYVISTA_OFF_SCREEN: false
  PYVISTA_JUPYTER_BACKEND: "html"
  LIBGL_ALWAYS_SOFTWARE: 1
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64 #,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for all images
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: fenics-wild-docs

      - name: Build documentation builder image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.webpage
          pull: false
          load: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: linux/amd64 #,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build documentation
        run: |
          docker run -v $(pwd):/root/shared -w /root/shared ${{ steps.metadata.outputs.tags }}

      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: documentation
          path: ${{ env.PUBLISH_DIR }}
          if-no-files-found: error
